[server]
host = "127.0.0.1"
port = 3000
timeout = "30s"
max_body_size = 10485760  # 10MB
cors = { enabled = true, allowed_origins = ["*"], allowed_methods = ["GET", "POST", "PUT", "DELETE"], allowed_headers = ["*"] }

# Development mode - set to false for production
development_mode = true

# Only include the provider we want to use for development
[providers.ollama]
name = "ollama"
api_key = ""
base_url = "http://localhost:11434"
timeout = "30s"
max_retries = 3
retry_delay = "1s"
enabled = true
model_mapping = {}
headers = {}

[routing]
strategy = { Single = {} }
health_check_interval = "30s"
failover_threshold = 0.8

[auth]
enabled = false
api_keys = []
rate_limiting = { requests_per_minute = 1000, requests_per_hour = 10000, tokens_per_minute = 100000 }

[cache]
enabled = true
backend = "Memory"
ttl = "1h"
max_size = 1000

[logging]
level = "info"
format = "Pretty"
output = "Stdout"

[metrics]
enabled = true
port = 9090
path = "/metrics"
max_requests = 1000
retention_duration = "24h"
cleanup_interval = "1h"

[[plugins]]
name = "cost_tracking"
enabled = true
config = { "track_costs" = true }
