// Writes <dir>/inline.ts exporting the .wasm as base64 (build tool, not part of src/).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = process.argv[2];
const b64 = readFileSync(join(dir, "ultrafast_client_wasm_bg.wasm")).toString("base64");
writeFileSync(join(dir, "inline.ts"), `// Generated by scripts/inline-wasm.mjs. Do not edit.\nexport const WASM_BASE64 = "${b64}";\n`);
