// Writes <dir>/inline.ts exporting the .wasm as base64 (build tool, not part of src/).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = process.argv[2];
const b64 = readFileSync(join(dir, "ultrafast_client_wasm_bg.wasm")).toString("base64");
writeFileSync(join(dir, "inline.ts"), `// Generated by scripts/inline-wasm.mjs. Do not edit.\nexport const WASM_BASE64: string = "${b64}";\n`);

// The glue's default (no source given) reaches for `new URL(..., import.meta.url)`, which bundlers
// follow to a file the package does not ship. initWasm always passes a source, so the branch goes.
const glue = join(dir, "ultrafast_client_wasm.js");
const text = readFileSync(glue, "utf8");
const branch = /    if \(module_or_path === undefined\) \{\n[^\n]*import\.meta\.url[^\n]*\n    \}\n/;
if (!branch.test(text)) throw new Error("the wasm-bindgen glue changed: update inline-wasm.mjs");
writeFileSync(glue, text.replace(branch, '    if (module_or_path === undefined) throw new TypeError("a wasm source is required");\n'));
