# Development Configuration - Testing Optimized
# Perfect for running tests and debugging

[server]
host = "127.0.0.1"
port = 3000
timeout = "10s"  # Shorter timeout for testing
max_body_size = 1048576  # 1MB for testing
cors = { enabled = true, allowed_origins = ["*"], allowed_methods = ["GET", "POST", "PUT", "DELETE"], allowed_headers = ["*"] }

# Ollama Provider (Local)
[providers.ollama]
name = "ollama"
api_key = ""  # No API key needed for local Ollama
base_url = "http://localhost:11434"
timeout = 10000  # 10 seconds for testing
max_retries = 2  # Fewer retries for testing
retry_delay = 500  # 0.5 seconds for testing
enabled = true
model_mapping = {}
headers = {}

# Simple routing for testing
[routing]
strategy = { Single = {} }  # Single provider for testing
health_check_interval = "10s"  # More frequent health checks
failover_threshold = 0.5  # Lower threshold for testing

# Authentication (enabled for testing)
[auth]
enabled = true
api_keys = [
    { 
        key = "sk-test-key", 
        name = "test", 
        enabled = true, 
        rate_limit = { 
            requests_per_minute = 1000,  # High limit for testing
            requests_per_hour = 10000, 
            tokens_per_minute = 100000 
        }, 
        metadata = {} 
    }
]
rate_limiting = { 
    requests_per_minute = 10000,  # High limits for testing
    requests_per_hour = 100000, 
    tokens_per_minute = 1000000 
}

# Caching for testing (shorter TTL)
[cache]
enabled = true
backend = "Memory"
ttl = "5m"  # 5 minutes for testing
max_size = 100  # Smaller cache for testing

# Verbose logging for testing
[logging]
level = "debug"  # Debug level for testing
format = "Pretty"
output = "Stdout"

# Testing plugins
[[plugins]]
name = "logging"
enabled = true
config = { "log_requests" = true, "log_responses" = true, "log_errors" = true }

[[plugins]]
name = "cost_tracking"
enabled = true
config = { "track_costs" = true } 