[server]
host = "127.0.0.1"
port = 3000
timeout = "30s"
max_body_size = 10485760
cors = { enabled = true, allowed_origins = ["*"], allowed_methods = ["GET", "POST", "PUT", "DELETE"], allowed_headers = ["*"] }

[providers.ollama]
name = "ollama"
api_key = ""
base_url = "http://localhost:11434"
timeout = "30s"
max_retries = 3
retry_delay = "1s"
enabled = true
model_mapping = {}
headers = {}

[routing]
strategy = { Single = "ollama" }
health_check_interval = "30s"
failover_threshold = 0.8

[auth]
enabled = false
api_keys = []
rate_limiting = { requests_per_minute = 1000, requests_per_hour = 10000, tokens_per_minute = 100000 }

[cache]
enabled = true
backend = "Memory"
ttl = "1h"
max_size = 1000

[logging]
level = "info"
format = "Pretty"
output = "Stdout"

[metrics]
enabled = true
max_requests = 10000
retention_duration = "1h"
cleanup_interval = "5m"

[[plugins]]
name = "logging"
enabled = true
config = { "log_requests" = true, "log_responses" = false } 