# Ollama Only Configuration
# Perfect for local development with Ollama

[server]
host = "127.0.0.1"
port = 3000
timeout = "30s"
max_body_size = 10485760  # 10MB
cors = { enabled = true, allowed_origins = ["*"], allowed_methods = ["GET", "POST", "PUT", "DELETE"], allowed_headers = ["*"] }

# Ollama Provider (Local)
[providers.ollama]
name = "ollama"
api_key = ""  # No API key needed for local Ollama
base_url = "http://localhost:11434"
timeout = 30000  # 30 seconds in milliseconds
max_retries = 3
retry_delay = 1000  # 1 second in milliseconds
enabled = true
model_mapping = {}
headers = {}

# Single provider routing
[routing]
strategy = { Single = {} }  # Single provider
health_check_interval = "30s"
failover_threshold = 0.8

# Authentication (enabled for testing)
[auth]
enabled = true
api_keys = [
    { 
        key = "sk-ollama-key", 
        name = "ollama-user", 
        enabled = true, 
        rate_limit = { 
            requests_per_minute = 200, 
            requests_per_hour = 2000, 
            tokens_per_minute = 20000 
        }, 
        metadata = { "provider" = "ollama" } 
    }
]
rate_limiting = { 
    requests_per_minute = 2000, 
    requests_per_hour = 20000, 
    tokens_per_minute = 200000 
}

# Caching for Ollama
[cache]
enabled = true
backend = "Memory"
ttl = "1h"
max_size = 1000

# Logging for Ollama
[logging]
level = "info"
format = "Pretty"
output = "Stdout"

# Ollama-specific plugins
[[plugins]]
name = "cost_tracking"
enabled = true
config = { "track_costs" = true, "ollama_tracking" = true } 