-- The PostgreSQL schema, equal to SQLite migrations 0001 to 0015 applied in
-- order. Postgres numbering is its own: the next change here is 0002_*.sql,
-- whatever number the SQLite directory is at.
--
-- Differences from SQLite that are on purpose:
--  * ids are BIGINT identity columns (never given out again);
--  * every number is BIGINT and every flag a BIGINT 0/1, so a row decodes
--    the same on both databases;
--  * every TEXT column is COLLATE "C", so comparing and ordering text is byte
--    order, as in SQLite, whatever the database's locale is;
--  * timestamps are TEXT 'YYYY-MM-DD HH:MM:SS' in UTC, with the same default
--    as SQLite's datetime('now');
--  * BLOB is BYTEA.

CREATE TABLE providers (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT  NOT NULL DEFAULT 1,
    name        TEXT    COLLATE "C" NOT NULL,
    kind        TEXT    COLLATE "C" NOT NULL,
    base_url    TEXT    COLLATE "C" NOT NULL,
    credential  BYTEA,
    created_at  TEXT    COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    api_version TEXT    COLLATE "C",
    UNIQUE (org_id, name)
);

CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id         BIGINT NOT NULL DEFAULT 1,
    email          TEXT   COLLATE "C" NOT NULL,
    name           TEXT   COLLATE "C" NOT NULL,
    role           TEXT   COLLATE "C" NOT NULL CHECK (role IN ('admin', 'member')),
    status         TEXT   COLLATE "C" NOT NULL CHECK (status IN ('active', 'invited', 'disabled')),
    password_hash  TEXT   COLLATE "C",
    auth_provider  TEXT   COLLATE "C" NOT NULL DEFAULT 'password',
    external_id    TEXT   COLLATE "C",
    created_at     TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    last_active_at TEXT   COLLATE "C",
    UNIQUE (org_id, email)
);

-- One user per identity at an external sign-in provider. Password users keep
-- external_id NULL and are not constrained.
CREATE UNIQUE INDEX users_external ON users (org_id, auth_provider, external_id)
    WHERE external_id IS NOT NULL;

CREATE TABLE teams (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT NOT NULL DEFAULT 1,
    name        TEXT   COLLATE "C" NOT NULL,
    created_at  TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (org_id, name)
);

CREATE TABLE virtual_keys (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT NOT NULL DEFAULT 1,
    name        TEXT   COLLATE "C" NOT NULL,
    key_hash    TEXT   COLLATE "C" NOT NULL UNIQUE,
    display     TEXT   COLLATE "C" NOT NULL,
    expires_at  TEXT   COLLATE "C",
    revoked_at  TEXT   COLLATE "C",
    created_at  TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    team_id     BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    -- A JSON array of model and route names the key may call; NULL is no allowlist.
    allowed     TEXT   COLLATE "C",
    -- A JSON object of strings, NULL for none.
    tags        TEXT   COLLATE "C",
    -- Who made the key. No foreign key on purpose (see SQLite 0012).
    created_by  BIGINT,
    -- A key that a non-admin made for another user acts for its team only.
    team_only   BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE invites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT NOT NULL DEFAULT 1,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT   COLLATE "C" NOT NULL UNIQUE,
    expires_at  TEXT   COLLATE "C" NOT NULL,
    used_at     TEXT   COLLATE "C",
    created_at  TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE team_members (
    org_id   BIGINT NOT NULL DEFAULT 1,
    team_id  BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role     TEXT   COLLATE "C" NOT NULL CHECK (role IN ('lead', 'member')),
    PRIMARY KEY (team_id, user_id)
);

CREATE TABLE sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT NOT NULL DEFAULT 1,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    id_hash     TEXT   COLLATE "C" NOT NULL UNIQUE,
    csrf_token  TEXT   COLLATE "C" NOT NULL,
    expires_at  TEXT   COLLATE "C" NOT NULL,
    created_at  TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE access_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       BIGINT NOT NULL DEFAULT 1,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         TEXT   COLLATE "C" NOT NULL,
    token_hash   TEXT   COLLATE "C" NOT NULL UNIQUE,
    display      TEXT   COLLATE "C" NOT NULL,
    expires_at   TEXT   COLLATE "C",
    revoked_at   TEXT   COLLATE "C",
    last_used_at TEXT   COLLATE "C",
    created_at   TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id         BIGINT NOT NULL DEFAULT 1,
    at             TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    actor_user_id  BIGINT,
    actor_email    TEXT   COLLATE "C" NOT NULL,
    action         TEXT   COLLATE "C" NOT NULL,
    target_type    TEXT   COLLATE "C" NOT NULL,
    target_id      BIGINT,
    summary        TEXT   COLLATE "C" NOT NULL
);

CREATE INDEX idx_keys_user ON virtual_keys(user_id);
CREATE INDEX idx_keys_team ON virtual_keys(team_id);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_tokens_user ON access_tokens(user_id);
CREATE INDEX idx_audit_at ON audit_log(at);

-- The model catalog: which models each provider offers, which of them are
-- enabled, and who may call them.
CREATE TABLE models (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT NOT NULL DEFAULT 1,
    provider_id BIGINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    name        TEXT   COLLATE "C" NOT NULL,
    enabled     BIGINT NOT NULL DEFAULT 0,
    created_at  TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    -- Prices per one million tokens, in millionths of a dollar. NULL: unknown.
    input_price_micros  BIGINT,
    output_price_micros BIGINT,
    UNIQUE (provider_id, name)
);

-- A row with neither team nor user grants the model to everyone.
CREATE TABLE model_grants (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id   BIGINT NOT NULL DEFAULT 1,
    model_id BIGINT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    team_id  BIGINT REFERENCES teams(id) ON DELETE CASCADE,
    user_id  BIGINT REFERENCES users(id) ON DELETE CASCADE,
    CHECK (team_id IS NULL OR user_id IS NULL)
);

CREATE UNIQUE INDEX model_grants_unique
    ON model_grants (model_id, COALESCE(team_id, 0), COALESCE(user_id, 0));

-- Routes: a name a client can call that spreads requests over models, with
-- fallbacks, timeouts and a circuit breaker.
CREATE TABLE routes (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id                 BIGINT NOT NULL DEFAULT 1,
    name                   TEXT   COLLATE "C" NOT NULL,
    retries                BIGINT NOT NULL DEFAULT 2,
    first_token_timeout_ms BIGINT NOT NULL DEFAULT 30000,
    total_timeout_ms       BIGINT NOT NULL DEFAULT 300000,
    breaker_failures       BIGINT NOT NULL DEFAULT 5,
    breaker_window_s       BIGINT NOT NULL DEFAULT 60,
    breaker_open_s         BIGINT NOT NULL DEFAULT 30,
    created_at             TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    -- Whether the route is for every user.
    everyone               BIGINT NOT NULL DEFAULT 1,
    -- The exact-match response cache of the route.
    cache_enabled          BIGINT NOT NULL DEFAULT 0,
    cache_ttl_s            BIGINT NOT NULL DEFAULT 300,
    cache_scope            TEXT   COLLATE "C" NOT NULL DEFAULT 'team'
        CHECK (cache_scope IN ('team', 'key', 'user')),
    UNIQUE (org_id, name)
);

-- A deleted model leaves its targets with it.
CREATE TABLE route_targets (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    model_id BIGINT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    tier     TEXT   COLLATE "C" NOT NULL CHECK (tier IN ('primary','fallback')),
    weight   BIGINT NOT NULL DEFAULT 1,
    position BIGINT NOT NULL
);

CREATE INDEX route_targets_route ON route_targets (route_id);
CREATE INDEX route_targets_model ON route_targets (model_id);

-- `seq` is what SQLite's rowid is: the order the grants were made in.
CREATE TABLE route_grants (
    route_id BIGINT NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    team_id  BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    seq      BIGINT GENERATED ALWAYS AS IDENTITY,
    PRIMARY KEY (route_id, team_id)
);

-- Request logs: one row per authenticated /v1 call, metadata only.
CREATE TABLE request_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT NOT NULL DEFAULT 1,
    at            TEXT   COLLATE "C" NOT NULL,
    key_id        BIGINT,
    user_id       BIGINT,
    team_id       BIGINT,
    requested     TEXT   COLLATE "C" NOT NULL,
    endpoint      TEXT   COLLATE "C" NOT NULL,
    stream        BIGINT NOT NULL,
    status        BIGINT NOT NULL,
    provider      TEXT   COLLATE "C",
    model         TEXT   COLLATE "C",
    input_tokens  BIGINT,
    output_tokens BIGINT,
    cost_micros   BIGINT NOT NULL DEFAULT 0,
    priced        BIGINT NOT NULL DEFAULT 0,
    cached        BIGINT NOT NULL DEFAULT 0,
    duration_ms   BIGINT NOT NULL,
    -- A JSON array of the targets tried, in order.
    attempts      TEXT   COLLATE "C" NOT NULL,
    -- 1 when the tokens and cost of the row are an estimate.
    estimated     BIGINT NOT NULL DEFAULT 0,
    tags          TEXT   COLLATE "C"
);

CREATE INDEX request_logs_at ON request_logs (at);
CREATE INDEX request_logs_key ON request_logs (key_id, at);
CREATE INDEX request_logs_user ON request_logs (user_id, at);
CREATE INDEX request_logs_team ON request_logs (team_id, at);

CREATE TABLE settings (
    key   TEXT COLLATE "C" PRIMARY KEY,
    value TEXT COLLATE "C" NOT NULL
);

INSERT INTO settings (key, value) VALUES ('log_retention_days', '30');

-- Rate limits of the gateway, a team, a user or a key. Each limit is
-- optional: NULL is no limit of that kind.
CREATE TABLE rate_limits (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id              BIGINT NOT NULL DEFAULT 1,
    scope               TEXT   COLLATE "C" NOT NULL CHECK (scope IN ('gateway', 'team', 'user', 'key')),
    -- NULL for the gateway, the id of the team, user or key otherwise.
    scope_id            BIGINT,
    requests_per_minute BIGINT CHECK (requests_per_minute IS NULL OR requests_per_minute > 0),
    tokens_per_minute   BIGINT CHECK (tokens_per_minute IS NULL OR tokens_per_minute > 0),
    concurrent          BIGINT CHECK (concurrent IS NULL OR concurrent > 0),
    created_at          TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (org_id, scope, scope_id),
    CHECK ((scope = 'gateway') = (scope_id IS NULL))
);

-- NULLs are distinct in a UNIQUE constraint, so the gateway's single
-- limit needs this index to stay single.
CREATE UNIQUE INDEX idx_rate_limits_subject ON rate_limits (org_id, scope, COALESCE(scope_id, 0));

-- Spending budgets of the gateway, a team, a user or a key, per UTC
-- calendar period.
CREATE TABLE budgets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT NOT NULL DEFAULT 1,
    scope         TEXT   COLLATE "C" NOT NULL CHECK (scope IN ('gateway', 'team', 'user', 'key')),
    -- NULL for the gateway, the id of the team, user or key otherwise.
    scope_id      BIGINT,
    amount_micros BIGINT NOT NULL CHECK (amount_micros > 0),
    period        TEXT   COLLATE "C" NOT NULL CHECK (period IN ('daily', 'weekly', 'monthly')),
    action        TEXT   COLLATE "C" NOT NULL CHECK (action IN ('block', 'alert')),
    created_at    TEXT   COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (org_id, scope, scope_id, period),
    CHECK ((scope = 'gateway') = (scope_id IS NULL))
);

CREATE UNIQUE INDEX idx_budgets_subject ON budgets (org_id, scope, COALESCE(scope_id, 0), period);

-- What a budget has spent in one period; `period_start` is the UTC date the
-- period began on, as YYYY-MM-DD.
CREATE TABLE budget_usage (
    budget_id    BIGINT NOT NULL REFERENCES budgets (id) ON DELETE CASCADE,
    period_start TEXT   COLLATE "C" NOT NULL,
    spent_micros BIGINT NOT NULL DEFAULT 0,
    -- 1 once the alert of this period was written.
    alerted      BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (budget_id, period_start)
);

-- Alerts: where notifications go (channels), when they are made (rules),
-- what a rule has seen (state) and what was sent (events).
CREATE TABLE alert_channels (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id     BIGINT NOT NULL DEFAULT 1,
    name       TEXT   COLLATE "C" NOT NULL,
    kind       TEXT   COLLATE "C" NOT NULL CHECK (kind IN ('webhook','slack')),
    url_enc    BYTEA  NOT NULL,
    url_host   TEXT   COLLATE "C" NOT NULL,
    secret_enc BYTEA  NOT NULL,
    enabled    BIGINT NOT NULL DEFAULT 1,
    created_at TEXT   COLLATE "C" NOT NULL,
    UNIQUE (org_id, name)
);
CREATE TABLE alert_rules (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id     BIGINT NOT NULL DEFAULT 1,
    name       TEXT   COLLATE "C" NOT NULL,
    kind       TEXT   COLLATE "C" NOT NULL CHECK (kind IN ('budget','error_rate','circuit_open')),
    params     TEXT   COLLATE "C" NOT NULL,   -- JSON, validated per kind
    enabled    BIGINT NOT NULL DEFAULT 1,
    created_at TEXT   COLLATE "C" NOT NULL,
    UNIQUE (org_id, name)
);
CREATE TABLE alert_rule_channels (
    rule_id    BIGINT NOT NULL REFERENCES alert_rules(id) ON DELETE CASCADE,
    channel_id BIGINT NOT NULL REFERENCES alert_channels(id) ON DELETE CASCADE,
    PRIMARY KEY (rule_id, channel_id)
);
CREATE TABLE alert_state (       -- one row per rule and subject while known
    rule_id BIGINT NOT NULL REFERENCES alert_rules(id) ON DELETE CASCADE,
    subject TEXT   COLLATE "C" NOT NULL,   -- e.g. 'budget:12:2026-10-05', 'route:chat'
    firing  BIGINT NOT NULL,
    since   TEXT   COLLATE "C" NOT NULL,
    PRIMARY KEY (rule_id, subject)
);
CREATE TABLE alert_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id     BIGINT NOT NULL DEFAULT 1,
    rule_id    BIGINT REFERENCES alert_rules(id) ON DELETE SET NULL,
    rule_name  TEXT   COLLATE "C" NOT NULL,
    kind       TEXT   COLLATE "C" NOT NULL,
    subject    TEXT   COLLATE "C" NOT NULL,
    state      TEXT   COLLATE "C" NOT NULL CHECK (state IN ('firing','resolved','test')),
    summary    TEXT   COLLATE "C" NOT NULL,
    details    TEXT   COLLATE "C" NOT NULL,   -- JSON, metadata only
    at         TEXT   COLLATE "C" NOT NULL,
    deliveries TEXT   COLLATE "C" NOT NULL DEFAULT '[]'
);
CREATE INDEX alert_events_at ON alert_events (org_id, at);

-- The scope of a limit or a budget is not a foreign key (it points at one of
-- three tables), so what a deleted team or user leaves behind is removed
-- here. A deleted user or team also leaves the request logs' owner column
-- empty. These are the equivalents of SQLite's triggers 0007, 0008 and 0010.
CREATE FUNCTION uf_team_deleted() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM rate_limits WHERE scope = 'team' AND scope_id = OLD.id;
    DELETE FROM budgets WHERE scope = 'team' AND scope_id = OLD.id;
    UPDATE request_logs SET team_id = NULL WHERE team_id = OLD.id;
    RETURN NULL;
END;
$$;

CREATE FUNCTION uf_user_deleted() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM rate_limits WHERE scope = 'user' AND scope_id = OLD.id;
    DELETE FROM budgets WHERE scope = 'user' AND scope_id = OLD.id;
    UPDATE request_logs SET user_id = NULL WHERE user_id = OLD.id;
    RETURN NULL;
END;
$$;

CREATE TRIGGER team_deleted AFTER DELETE ON teams
    FOR EACH ROW EXECUTE FUNCTION uf_team_deleted();
CREATE TRIGGER user_deleted AFTER DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION uf_user_deleted();
