-- Guardrails: rules that block, redact or flag the text going to and coming
-- from models, or an external webhook that decides. A guardrail is attached
-- to routes and keys (in order), or made a gateway-wide default. This is
-- SQLite migration 0017.
CREATE TABLE guardrails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1,
  name TEXT COLLATE "C" NOT NULL, description TEXT COLLATE "C" NOT NULL DEFAULT '',
  kind TEXT COLLATE "C" NOT NULL CHECK (kind IN ('rules','external')),
  rules TEXT COLLATE "C" NOT NULL DEFAULT '[]',     -- JSON array of rules (kind 'rules')
  -- kind 'external': where to post (encrypted; only the host is shown), the
  -- signing secret (encrypted), how long to wait, what to do when it fails
  -- and which directions it is asked about.
  external_url_enc BYTEA, external_url_host TEXT COLLATE "C", external_secret_enc BYTEA,
  timeout_ms BIGINT NOT NULL DEFAULT 3000,
  fail_mode TEXT COLLATE "C" NOT NULL DEFAULT 'open' CHECK (fail_mode IN ('open','closed')),
  directions TEXT COLLATE "C" NOT NULL DEFAULT 'both' CHECK (directions IN ('input','output','both')),
  enabled BIGINT NOT NULL DEFAULT 1,
  is_default BIGINT NOT NULL DEFAULT 0,  -- applies to every call of the gateway
  created_at TEXT COLLATE "C" NOT NULL,
  UNIQUE (org_id, name));
CREATE TABLE route_guardrails (
  route_id BIGINT NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
  guardrail_id BIGINT NOT NULL REFERENCES guardrails(id) ON DELETE CASCADE,
  position BIGINT NOT NULL,
  PRIMARY KEY (route_id, guardrail_id));
CREATE INDEX route_guardrails_guardrail ON route_guardrails (guardrail_id);
CREATE TABLE key_guardrails (
  key_id BIGINT NOT NULL REFERENCES virtual_keys(id) ON DELETE CASCADE,
  guardrail_id BIGINT NOT NULL REFERENCES guardrails(id) ON DELETE CASCADE,
  position BIGINT NOT NULL,
  PRIMARY KEY (key_id, guardrail_id));
CREATE INDEX key_guardrails_guardrail ON key_guardrails (guardrail_id);
-- What the guardrails did to a call: a JSON outcome of ids, actions and
-- counts. Never the text that matched.
ALTER TABLE request_logs ADD COLUMN guardrails TEXT COLLATE "C";
