-- Prompt templates: named, versioned messages with {{variables}}, rendered
-- into a call by name. A version never changes once written; a new text is a
-- new version. Deleting a template deletes its versions; the request log
-- keeps only the text name@version, so it survives. This is SQLite
-- migration 0018.
CREATE TABLE prompt_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL DEFAULT 1,
  name TEXT COLLATE "C" NOT NULL, description TEXT COLLATE "C" NOT NULL DEFAULT '',
  -- Who made it (a team lead manages the templates they made). The user
  -- going away leaves it to the admins.
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT COLLATE "C" NOT NULL,
  UNIQUE (org_id, name));
CREATE TABLE prompt_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL REFERENCES prompt_templates(id) ON DELETE CASCADE,
  version BIGINT NOT NULL,
  messages TEXT COLLATE "C" NOT NULL,                 -- JSON array of {role, content}
  variables TEXT COLLATE "C" NOT NULL DEFAULT '[]',   -- JSON array of the names the messages use
  model TEXT COLLATE "C",                             -- used when the call names none
  params TEXT COLLATE "C" NOT NULL DEFAULT '{}',      -- JSON: temperature, max_tokens, top_p, response_format
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT COLLATE "C" NOT NULL,
  UNIQUE (template_id, version));
-- Immutable: the text of a version cannot be updated, whoever asks.
CREATE FUNCTION prompt_versions_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'prompt versions never change';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER prompt_versions_immutable
  BEFORE UPDATE OF template_id, version, messages, variables, model, params ON prompt_versions
  FOR EACH ROW EXECUTE FUNCTION prompt_versions_immutable();
-- The template and version a call used, as name@version. Text, not a
-- reference: it outlives the template.
ALTER TABLE request_logs ADD COLUMN prompt TEXT COLLATE "C";
